<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{719519df-59da-4ee1-b75d-42692bd0c354}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	b1: BOOL;
	b2:BOOL;
	c1: BOOL;

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[b1:=FALSE;
b2:=TRUE;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>